"""rag_chunks for mentor retrieval

Revision ID: fccb348abe62
Revises: 4a6f17d95c7b
Create Date: 2026-07-28 02:27:22.726370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fccb348abe62'
down_revision: Union[str, None] = '4a6f17d95c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_slug', sa.String(), nullable=False),
    sa.Column('source_title', sa.String(), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('anchor', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_chunks_content_hash'), 'rag_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_rag_chunks_source_slug'), 'rag_chunks', ['source_slug'], unique=False)
    op.create_index(op.f('ix_rag_chunks_source_type'), 'rag_chunks', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_chunks_source_type'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_source_slug'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_content_hash'), table_name='rag_chunks')
    op.drop_table('rag_chunks')
    # ### end Alembic commands ###
